### ISSUE TITLE
Runtime Exception in BoxTester

### ISSUE THREAD

**Issue by karlnicholas** [CS111C-META-FALL-2016/week2#1]
I got an exception when I ran BoxTester out of the box, so to speak.

Exception in thread "main" java.lang.ClassCastException: [Ljava.lang.Object; cannot be cast to [Ljava.lang.Comparable;
	at Box.<init>(Box.java:14)
	at BoxTester.main(BoxTester.java:14)

This under Java 1.8.0_102. I The problem seems to be the new Object being allocated for an array of <T extends Comparable<? super T>>. Will look closer later, have a 9:10 class.

**Comment by karlnicholas** [comment]
Solution here:
http://stackoverflow.com/questions/529085/how-to-create-a-generic-array-in-java

which leads to:

oldThings = (T[]) Array.newInstance(firstThing.getClass(), 5);

**Comment by karlnicholas** [comment]
Yup- you're right. That line was in there from the video where I talked about not being able to create an array. But it is incompatible with the modified header. (The reason relates to wildcard bounds.)

You can replace the line with: oldThings = (T[]) (new Comparable[5]); // allowed

I've also updated the source code zip with this change.

(Note you could use the "new Object" original line if you did not require the Box to hold Comparable objects.)

**Comment by karlnicholas** [comment]
oldThings = (T[]) (new Comparable[5]);

Nice, I didn't think of that. It's all so much easier with Collections.
